//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/28/2010 10:28:51 PM
namespace Hayman.Client.HaymanReadModelServiceReference
{
    
    /// <summary>
    /// There are no comments for HaymanReadModelEntities in the schema.
    /// </summary>
    public partial class HaymanReadModelEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new HaymanReadModelEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HaymanReadModelEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("HaymanReadModelModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Hayman.Client.HaymanReadModelServiceReference", typeName.Substring(20)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Hayman.Client.HaymanReadModelServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("HaymanReadModelModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for MetaAssociations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MetaAssociation> MetaAssociations
        {
            get
            {
                if ((this._MetaAssociations == null))
                {
                    this._MetaAssociations = base.CreateQuery<MetaAssociation>("MetaAssociations");
                }
                return this._MetaAssociations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MetaAssociation> _MetaAssociations;
        /// <summary>
        /// There are no comments for MetaItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MetaItem> MetaItems
        {
            get
            {
                if ((this._MetaItems == null))
                {
                    this._MetaItems = base.CreateQuery<MetaItem>("MetaItems");
                }
                return this._MetaItems;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MetaItem> _MetaItems;
        /// <summary>
        /// There are no comments for MetaModels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MetaModel> MetaModels
        {
            get
            {
                if ((this._MetaModels == null))
                {
                    this._MetaModels = base.CreateQuery<MetaModel>("MetaModels");
                }
                return this._MetaModels;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MetaModel> _MetaModels;
        /// <summary>
        /// There are no comments for MetaAssociations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMetaAssociations(MetaAssociation metaAssociation)
        {
            base.AddObject("MetaAssociations", metaAssociation);
        }
        /// <summary>
        /// There are no comments for MetaItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMetaItems(MetaItem metaItem)
        {
            base.AddObject("MetaItems", metaItem);
        }
        /// <summary>
        /// There are no comments for MetaModels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMetaModels(MetaModel metaModel)
        {
            base.AddObject("MetaModels", metaModel);
        }
    }
    /// <summary>
    /// There are no comments for HaymanReadModelModel.MetaAssociation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MetaAssociationId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MetaAssociations")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MetaAssociationId")]
    public partial class MetaAssociation : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MetaAssociation object.
        /// </summary>
        /// <param name="metaAssociationId">Initial value of MetaAssociationId.</param>
        /// <param name="metaItemSourceId">Initial value of MetaItemSourceId.</param>
        /// <param name="metaItemTargetId">Initial value of MetaItemTargetId.</param>
        /// <param name="deleted">Initial value of Deleted.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MetaAssociation CreateMetaAssociation(global::System.Guid metaAssociationId, global::System.Guid metaItemSourceId, global::System.Guid metaItemTargetId, bool deleted)
        {
            MetaAssociation metaAssociation = new MetaAssociation();
            metaAssociation.MetaAssociationId = metaAssociationId;
            metaAssociation.MetaItemSourceId = metaItemSourceId;
            metaAssociation.MetaItemTargetId = metaItemTargetId;
            metaAssociation.Deleted = deleted;
            return metaAssociation;
        }
        /// <summary>
        /// There are no comments for Property MetaAssociationId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaAssociationId
        {
            get
            {
                return this._MetaAssociationId;
            }
            set
            {
                this.OnMetaAssociationIdChanging(value);
                this._MetaAssociationId = value;
                this.OnMetaAssociationIdChanged();
                this.OnPropertyChanged("MetaAssociationId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaAssociationId;
        partial void OnMetaAssociationIdChanging(global::System.Guid value);
        partial void OnMetaAssociationIdChanged();
        /// <summary>
        /// There are no comments for Property MetaItemSourceId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaItemSourceId
        {
            get
            {
                return this._MetaItemSourceId;
            }
            set
            {
                this.OnMetaItemSourceIdChanging(value);
                this._MetaItemSourceId = value;
                this.OnMetaItemSourceIdChanged();
                this.OnPropertyChanged("MetaItemSourceId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaItemSourceId;
        partial void OnMetaItemSourceIdChanging(global::System.Guid value);
        partial void OnMetaItemSourceIdChanged();
        /// <summary>
        /// There are no comments for Property MetaItemTargetId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaItemTargetId
        {
            get
            {
                return this._MetaItemTargetId;
            }
            set
            {
                this.OnMetaItemTargetIdChanging(value);
                this._MetaItemTargetId = value;
                this.OnMetaItemTargetIdChanged();
                this.OnPropertyChanged("MetaItemTargetId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaItemTargetId;
        partial void OnMetaItemTargetIdChanging(global::System.Guid value);
        partial void OnMetaItemTargetIdChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Deleted;
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for MetaItemSource in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MetaItem MetaItemSource
        {
            get
            {
                return this._MetaItemSource;
            }
            set
            {
                this._MetaItemSource = value;
                this.OnPropertyChanged("MetaItemSource");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MetaItem _MetaItemSource;
        /// <summary>
        /// There are no comments for MetaItemTarget in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MetaItem MetaItemTarget
        {
            get
            {
                return this._MetaItemTarget;
            }
            set
            {
                this._MetaItemTarget = value;
                this.OnPropertyChanged("MetaItemTarget");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MetaItem _MetaItemTarget;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for HaymanReadModelModel.MetaItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MetaItemId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MetaItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MetaItemId")]
    public partial class MetaItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MetaItem object.
        /// </summary>
        /// <param name="metaItemId">Initial value of MetaItemId.</param>
        /// <param name="metaItemName">Initial value of MetaItemName.</param>
        /// <param name="metaModelId">Initial value of MetaModelId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MetaItem CreateMetaItem(global::System.Guid metaItemId, string metaItemName, global::System.Guid metaModelId)
        {
            MetaItem metaItem = new MetaItem();
            metaItem.MetaItemId = metaItemId;
            metaItem.MetaItemName = metaItemName;
            metaItem.MetaModelId = metaModelId;
            return metaItem;
        }
        /// <summary>
        /// There are no comments for Property MetaItemId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaItemId
        {
            get
            {
                return this._MetaItemId;
            }
            set
            {
                this.OnMetaItemIdChanging(value);
                this._MetaItemId = value;
                this.OnMetaItemIdChanged();
                this.OnPropertyChanged("MetaItemId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaItemId;
        partial void OnMetaItemIdChanging(global::System.Guid value);
        partial void OnMetaItemIdChanged();
        /// <summary>
        /// There are no comments for Property MetaItemName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MetaItemName
        {
            get
            {
                return this._MetaItemName;
            }
            set
            {
                this.OnMetaItemNameChanging(value);
                this._MetaItemName = value;
                this.OnMetaItemNameChanged();
                this.OnPropertyChanged("MetaItemName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MetaItemName;
        partial void OnMetaItemNameChanging(string value);
        partial void OnMetaItemNameChanged();
        /// <summary>
        /// There are no comments for Property MetaModelId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaModelId
        {
            get
            {
                return this._MetaModelId;
            }
            set
            {
                this.OnMetaModelIdChanging(value);
                this._MetaModelId = value;
                this.OnMetaModelIdChanged();
                this.OnPropertyChanged("MetaModelId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaModelId;
        partial void OnMetaModelIdChanging(global::System.Guid value);
        partial void OnMetaModelIdChanged();
        /// <summary>
        /// There are no comments for IncomingMetaAssociations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<MetaAssociation> IncomingMetaAssociations
        {
            get
            {
                return this._IncomingMetaAssociations;
            }
            set
            {
                this._IncomingMetaAssociations = value;
                this.OnPropertyChanged("IncomingMetaAssociations");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<MetaAssociation> _IncomingMetaAssociations = new global::System.Data.Services.Client.DataServiceCollection<MetaAssociation>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for OutgoingMetaAssociations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<MetaAssociation> OutgoingMetaAssociations
        {
            get
            {
                return this._OutgoingMetaAssociations;
            }
            set
            {
                this._OutgoingMetaAssociations = value;
                this.OnPropertyChanged("OutgoingMetaAssociations");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<MetaAssociation> _OutgoingMetaAssociations = new global::System.Data.Services.Client.DataServiceCollection<MetaAssociation>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for MetaModel in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MetaModel MetaModel
        {
            get
            {
                return this._MetaModel;
            }
            set
            {
                this._MetaModel = value;
                this.OnPropertyChanged("MetaModel");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MetaModel _MetaModel;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for HaymanReadModelModel.MetaModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MetaModelId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MetaModels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MetaModelId")]
    public partial class MetaModel : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MetaModel object.
        /// </summary>
        /// <param name="metaModelId">Initial value of MetaModelId.</param>
        /// <param name="metaModelName">Initial value of MetaModelName.</param>
        /// <param name="deleted">Initial value of Deleted.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MetaModel CreateMetaModel(global::System.Guid metaModelId, string metaModelName, bool deleted)
        {
            MetaModel metaModel = new MetaModel();
            metaModel.MetaModelId = metaModelId;
            metaModel.MetaModelName = metaModelName;
            metaModel.Deleted = deleted;
            return metaModel;
        }
        /// <summary>
        /// There are no comments for Property MetaModelId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid MetaModelId
        {
            get
            {
                return this._MetaModelId;
            }
            set
            {
                this.OnMetaModelIdChanging(value);
                this._MetaModelId = value;
                this.OnMetaModelIdChanged();
                this.OnPropertyChanged("MetaModelId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _MetaModelId;
        partial void OnMetaModelIdChanging(global::System.Guid value);
        partial void OnMetaModelIdChanged();
        /// <summary>
        /// There are no comments for Property MetaModelName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MetaModelName
        {
            get
            {
                return this._MetaModelName;
            }
            set
            {
                this.OnMetaModelNameChanging(value);
                this._MetaModelName = value;
                this.OnMetaModelNameChanged();
                this.OnPropertyChanged("MetaModelName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MetaModelName;
        partial void OnMetaModelNameChanging(string value);
        partial void OnMetaModelNameChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Deleted;
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for MetaItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<MetaItem> MetaItems
        {
            get
            {
                return this._MetaItems;
            }
            set
            {
                this._MetaItems = value;
                this.OnPropertyChanged("MetaItems");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<MetaItem> _MetaItems = new global::System.Data.Services.Client.DataServiceCollection<MetaItem>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
