//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayman.Client.HaymanCommandServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HaymanCommandServiceReference.IHaymanCommandService")]
    public interface IHaymanCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHaymanCommandService/ExecuteCommand", ReplyAction="http://tempuri.org/IHaymanCommandService/ExecuteCommandResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Ncqrs.Commanding.CommandBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.CreateMetaModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.DeleteMetaAssociation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.CreateMetaAssociation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.RemoveMetaItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.AddItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.AddAssociation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.AddMetaItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.RenameMetaModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hayman.Commands.DeleteMetaModel))]
        void ExecuteCommand(object command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHaymanCommandServiceChannel : Hayman.Client.HaymanCommandServiceReference.IHaymanCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HaymanCommandServiceClient : System.ServiceModel.ClientBase<Hayman.Client.HaymanCommandServiceReference.IHaymanCommandService>, Hayman.Client.HaymanCommandServiceReference.IHaymanCommandService {
        
        public HaymanCommandServiceClient() {
        }
        
        public HaymanCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HaymanCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HaymanCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HaymanCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExecuteCommand(object command) {
            base.Channel.ExecuteCommand(command);
        }
    }
}
